name: "ConnectIQ Builder"
description: "Test and build a ConnectIQ application"
inputs:
  path:
    description: "The path of the application to test"
    required: true
    default: .
  device:
    description: "The id of the device used to run the tests"
    required: true
    default: fenix7
  # certificate:
  #   description: "The path of the certificate used to compile the application relatively to the path of the application"
  #   required: false
outputs:
  status:
    description: "'success' if tests succeeded, 'failure' if not"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{inputs.path}}"
    - ${{inputs.device}}
    - ${{inputs.certificate}}
branding:
  icon: "triangle"
  color: "orange"
