name: "ConnectIQ Builder"
description: "Test and build a ConnectIQ application."
inputs:
  operation:
    description: "The name of the operation to run (INFO|TEST|PACKAGE)."
    required: true
    default: TEST
  path:
    description: "The path of the application to test or build."
    required: true
    default: .
  device:
    description: "The device ID used to run the test or build process."
    required: true
    default: fr235
  type_check_level:
    description: "The type check level to use when compiling the application (0-3)."
    required: true
    default: 2
  certificate:
    description: "The base64 encoded certificate to use to test or build the application."
    required: false
  package_name:
    description: "The file name of the package that is built when operation mode is PACKAGE."
    required: false
outputs:
  status:
    description: "'success' if tests succeeded, 'failure' if not"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.operation}}
    - ${{inputs.path}}
    - ${{inputs.device}}
    - ${{inputs.type_check_level}}
    - ${{inputs.certificate}}
    - ${{inputs.package_name}}
branding:
  icon: "package"
  color: "orange"
